"""empty message

Revision ID: d574a6089401
Revises: 
Create Date: 2022-08-24 21:34:59.224103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd574a6089401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_course_student_id_fkey', 'student_course', type_='foreignkey')
    op.create_foreign_key(None, 'student_course', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.create_foreign_key('student_course_student_id_fkey', 'student_course', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
